name: shoppazing_rider_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.8.0
  url_launcher: ^6.3.0  
  intl: ^0.19.0          
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/         # This includes all images in that folder
    - assets/shoppazing_logo.jpg  # If this file exists in root assets